# Reusable workflow to deploy a helm chart

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to K8s
    steps:
      - name: Configure AWS credentials in ENV
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Helm deploy
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          aws eks update-kubeconfig --name eks-demo
          helm upgrade demo --set registry=$REGISTRY --install --wait --atomic oci://$REGISTRY/demo-chart
